electricity:
  username: test_admin
  password: test
  host: localhost
  port: 5432
  database: energy

warmth:
  username: test_admin
  password: test
  host: localhost
  port: 5432
  database: warmth