electricity:
  username: test_admin
  password: test
  host: localhost
  port: 5432
  database: energy

warmth:
  username: administrator
  password: Sv255366313
  host: localhost
  port: 5432
  database: warmth

boiler:
  username: administrator
  password: Sv255366313
  host: localhost
  port: 5432
  database: boiler